name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }} # <-- set here
    steps:
      - uses: actions/checkout@v2

      - name: Install deps & run tests
        working-directory: payments
        run: |
          npm install
          npm run test:ci
